/* Generated by CIL v. 1.3.6 */
/* print_CIL_Input is true */

#line 3 "justoneif.c"
typedef int bool;
#line 363 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
#line 4 "justoneif.c"
int (*g)(void)  ;
#line 6 "justoneif.c"
void f(void) 
{ bool i ;
  bool j ;

  {
#line 7
  j = 0;
#line 9
  if (i == j) {
#line 10
    i = j * j;
  } else {
    {

    }
  }
  goto __dyc_dummy_label;
}
}
