#!/usr/bin/python2.4

import re
import sys
import deckardfiltering
import clustertrunknames

def gettrunknames( names, cluster ):
    rs = map(deckardfiltering.vector_linerange, cluster)
    for i in range(len(rs)):
        names.add(clustertrunknames.codetrunkname(rs[i][0]))
    return names

if len(sys.argv) != 2:
    print "Usage: ", sys.argv[0], " <orig clone reports>"
    sys.exit(1)

clusters = deckardfiltering.readclusters( sys.argv[1] )
clusters= list(reduce(gettrunknames, clusters, set()))
clusters.sort()
for n in clusters:
    print n


