#!/usr/bin/python2.4

#no 64-bit psyco yet...03/11/07
#import psyco
#psyco.full()

import sys, os
import clusterfiltering

f= open(sys.argv[1])  # a list file containing all L* files, each of which is a cluster

fileCoverSet={}
ccc=0
cvc=0

for line in f:  # one cluster
    line = line.splitlines()
    if len(line)<1:
       continue
    line = line[len(line)-1]
    line = line.split()
    if len(line)<1:
       continue
    line = line[len(line)-1]
    ff = open(line)
    cluster = ff.readlines()
    cluster = clusterfiltering.filter_duplicated_functions(cluster)
    cluster.sort()
    ff.close()
    if len(cluster)<=1:
       continue

    ccc += 1
    for c in cluster:
        cvc += 1
        loc = clusterfiltering.getlocations(c)
        if loc[2][0]<=0:
           print >> sys.stderr, "bad line number:", loc[0], loc[1], loc[2]
           continue
        if loc[0] not in fileCoverSet: # this may not be right...the overlapping across different clusters are not taken into account...TODO
           fileCoverSet[loc[0]] = set()
        fileCoverSet[loc[0]].update(range(loc[2][0], loc[2][2]+1))

f.close()

sum = 0
for file,coverset in fileCoverSet.items():
    #print file,',',coverset
    sum += len(coverset)

print "clusters:", ccc, " vectors:", cvc
print "LoC:", sum

