#!/bin/bash

if [[ $# -ne 3 ]]; then
    echo "Usage: $0 <src dir> <dstlist> <limit for each function>"
    exit 65
fi

if [[ ! -d "$1" ]]; then
    echo "Error: src dir '$1' invalid"
    exit 65
fi
if [[ ! -d `dirname $2` ]]; then
    echo "Error: dst dir for '$2' invalid"
    exit 65
fi
if [[ -d "$2" ]]; then
    echo "Error: '$2' can not be a directory!"
    exit 1
fi
if [[ -e "$2" ]]; then
    echo "Warning: '$2' exists. Length: `wc -l $2`. Append to it......"
fi

scriptdir=$(cd `dirname $0`; pwd)
abspath=$( cd $1; pwd )
linklimit=$3
 
ls "$abspath" | while read fd; do
    fd=$abspath/$fd
    if [ -d $fd ]; then
        tmpfile=`mktemp`
        find "$fd" -name "*.foo.rds" | while read fn; do
            fooc=${fn%.rds}.c
            ins=${fn%.rds}.ins
            ins=`tail -n 1 $ins`
            rds=$fn  #${fn%.c}.rds
            rds=`tail -n 1 $rds`
            echo "$fooc|$ins|$rds" >> "$tmpfile"
        done
        $scriptdir/shuffle $tmpfile $linklimit >> "$2"
        rm $tmpfile
    fi
done

#$scriptdir/groupcodelist "$2" "$2"
#i=1
#while read l; do
#    mkdir -p `dirname $2`/l$i/0/CLSRTT.0.0 && mv "$l" `dirname $2`/l$i/0/CLSRTT.0.0/L0
#    i=$((i+1))
#done < <( find `dirname $2` -name "`basename $2`\(*" )

#$scriptdir/sortcodelist "$2" > "$2.sorted"
#mv "$2.sorted" "$2"

